### ISSUE TITLE
Exponential fit not working

### ISSUE THREAD

**Issue by jstitlow** [jstitlow/GPU_FIJI_plugin#2]
@haesleinhuepf, do you have the same issue?
Current version of the code and a test image are included in this repo. 
Thanks!
j

**Exponential Fit method gives erroneous fit values:**
Formula: y = a*exp(-bx) + c
Macro code: y = a*Math.exp(-b*x)+c
Status: Success
Number of completed minimizations: 4
Number of iterations: 198 (max: 1500)
Time: 1 ms
Sum of residuals squared: 16495.1038
Standard deviation: 20.35748
R^2: 1.00000
Parameters:
	a = 436016534
	b = 17.11486
	c = 1642.41269

**Here are what the values should be:**
Formula: y = a*exp(-bx) + c
Macro code: y = a*Math.exp(-b*x)+c
Status: Success
Number of completed minimizations: 2
Number of iterations: 46 (max: 1500)
Time: 1 ms
Sum of residuals squared: 186.05112
Standard deviation: 2.15668
R^2: 0.98926
Parameters:
	a = -0.69357
	b = -0.11806
	c = 1660.27941

**Comment by haesleinhuepf** [comment]
Hey @jstitlow ,

I haven't tried for some time. Just a quick guess: Does the error also happen if the input images are 32 bit?

For debugging, I would check if the numbers in [this array](https://github.com/jstitlow/GPU_FIJI_plugin/blob/master/src/main/java/com/yourdomain/clijplugin/BleachCorrection.java#L100) make sense. The rest of the exponential fitting code should be identical to the original code in Fiji, right?

Furthermore, consider updating to [CLIJ2](https://clij.github.io/) (Even though I don't think this is the issue....).

Let me know if I can help further!

Best,
Robert

**Comment by jstitlow** [comment]
Thanks for the input. 

Error still occurs with 32 bit image. 

The array looks fine, should work fine too, as it is the same array used in the Simple Ratio method. 

As you said, the rest of the fitting code is copied directly from the Fiji code. 

**The fitting is done by curvefitting, is that function completed on the GPU, and could it be causing an issue?**

Still working on [porting to clij2](https://github.com/jstitlow/BleachCorrection_clij2), but it's not showing up in ImageJ when I build it with maven.

**Comment by haesleinhuepf** [comment]
> The fitting is done by curvefitting, is that function completed on the GPU, and could it be causing an issue?

Not sure if I understand. [This](https://github.com/jstitlow/GPU_FIJI_plugin/blob/master/src/main/java/com/yourdomain/clijplugin/BleachCorrection.java#L125) class is identical with the original implementation. Thus, it should do the same. I'd recommend outputing more intermediate results to find out where exactly the error sits.



> but it's not showing up in ImageJ when I build it with maven.

Try copying [this](https://github.com/jstitlow/GPU_FIJI_plugin/blob/master/pom.xml#L80) line [here](https://github.com/jstitlow/BleachCorrection_clij2/blob/master/pom.xml#L77).



> Still working on [porting to clij2](https://github.com/jstitlow/BleachCorrection_clij2)

Awesome! Looking forward to see this growing. If you want to learn more CLIJ2, feel free to [sign up](https://janeliaconf.smapply.io/prog/i2k2020/) for the [I2K tutorial](https://www.janelia.org/sites/default/files/You%20%2B%20Janelia/Conferences/9.pdf).

Cheers,
Robert

**Comment by jstitlow** [comment]
Thanks, the issue was caused by a bad array in the end. Starting [this loop](https://github.com/jstitlow/GPU_FIJI_plugin/blob/master/src/main/java/com/yourdomain/clijplugin/BleachCorrection.java#L117) at 0 instead of 1 did the trick. 

[BleachCorrection2 for clij2](https://github.com/jstitlow/BleachCorrection_clij2) is also up and running. Will let you know when the histogram matching method is added. 

Registered for the I2K tutorial.

See you at the end of the month!
j
